# Generated by Django 5.2.9 on 2026-07-12 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_description_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimate_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Rough time estimate, for planning your week', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='The day you plan to do this task', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('done', 'Done')], default='planned', max_length=20),
        ),
        migrations.AddField(
            model_name='worksession',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Optional: the specific task this work was against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_sessions', to='projects.task'),
        ),
    ]
