# Generated by Django 5.2.16 on 2026-07-16 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_backfill_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.CharField(choices=[('none', 'One-off'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', help_text='A habit that repeats. Completion is tracked per day/week/month instead of once.', max_length=10),
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='Day, Monday-of-week, or 1st-of-month this completion covers')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='projects.task')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('task', 'period_start')},
            },
        ),
    ]
