# Generated by Django 5.2.16 on 2026-07-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_task_recurrence_taskcompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('none', 'One-off'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', help_text='A habit that repeats. Completion is tracked per day/week/month instead of once.', max_length=10),
        ),
    ]
