# Generated by Django 5.1 on 2025-03-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Project Tracker', max_length=100)),
                ('site_description', models.TextField(blank=True, default='A tool for tracking your projects and tasks')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('enable_work_timer', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('default_og_image', models.ImageField(blank=True, help_text='Default image for social media sharing (1200x630px recommended)', null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
