# Generated by Django 5.1 on 2025-03-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
