# Generated by Django 5.2.9 on 2026-07-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfiguration_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='anthropic_api_key',
            field=models.CharField(blank=True, help_text='Your Anthropic API key (starts with sk-ant-...). Get one at console.anthropic.com. Leave blank to disable AI content generation.', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='anthropic_default_model',
            field=models.CharField(blank=True, help_text='Optional. Leave blank to use the default model.', max_length=100),
        ),
    ]
