# Generated by Django 5.2.9 on 2026-07-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfiguration_anthropic_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='anthropic_api_key',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='anthropic_default_model',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ai_api_key',
            field=models.CharField(blank=True, help_text='Your API key for the provider selected above. Leave blank to disable AI content generation.', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ai_model',
            field=models.CharField(blank=True, help_text='Optional. Leave blank to use a sensible default for the selected provider.', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ai_provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (ChatGPT)'), ('gemini', 'Google (Gemini)')], default='anthropic', help_text='Which AI provider your API key below is for.', max_length=20),
        ),
    ]
