# Generated by Django 5.2.9 on 2026-07-17 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0004_remove_contact_joined_live_it_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Email sequences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Plain text or simple HTML')),
                ('delay_days', models.PositiveIntegerField(default=0, help_text='Days after enrollment to send this step')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='sequences.emailsequence')),
            ],
            options={
                'ordering': ['sequence', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SequenceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_enrollments', to='crm.contact')),
                ('last_step_sent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sequences.emailstep')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='sequences.emailsequence')),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('sequence', 'contact')},
            },
        ),
    ]
