# Generated by Django 5.2.9 on 2026-07-17 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0004_remove_contact_joined_live_it_list_and_more'),
        ('pages', '0001_initial'),
        ('projects', '0008_alter_task_recurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('content_type', models.CharField(choices=[('blog', 'Blog post'), ('social', 'Social media'), ('email', 'Email'), ('funnel', 'Funnel / sales copy'), ('docs', 'Documentation'), ('general', 'General')], default='general', max_length=20)),
                ('system_prompt', models.TextField(help_text='Instructions given to the AI before your asset content')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['content_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, help_text='Optional: upload the original file (PDF, doc, image, audio, etc.)', null=True, upload_to='assets/')),
                ('file_type', models.CharField(choices=[('text', 'Text'), ('markdown', 'Markdown'), ('pdf', 'PDF'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('other', 'Other')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Pasted text/transcript, or text extracted from the uploaded file. This is what actually gets sent to the AI — the file itself is just for reference.')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated', max_length=255)),
                ('token_count', models.PositiveIntegerField(default=0, help_text='Rough estimate (chars / 4), for planning what fits in a prompt — not billing-accurate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='crm.contact')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='projects.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My voice', max_length=150)),
                ('summary', models.TextField(blank=True, help_text='One or two sentence summary of the voice')),
                ('tone_words', models.JSONField(blank=True, default=list)),
                ('sentence_length', models.CharField(choices=[('short', 'Short & punchy'), ('medium', 'Medium'), ('long', 'Long & flowing'), ('varied', 'Varied')], default='varied', max_length=10)),
                ('words_to_avoid', models.JSONField(blank=True, default=list)),
                ('sample_paragraphs', models.JSONField(blank=True, default=list)),
                ('do_notes', models.JSONField(blank=True, default=list)),
                ('dont_notes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True, help_text='Used as the default voice when generating content, if none is chosen explicitly')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_assets', models.ManyToManyField(blank=True, related_name='voice_profiles', to='assets.asset')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True, help_text='Extra one-off instructions for this run')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assets', models.ManyToManyField(related_name='generation_jobs', to='assets.asset')),
                ('result_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_job', to='pages.page')),
                ('prompt_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='assets.prompttemplate')),
                ('voice_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='assets.voiceprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
