# Generated by Django 5.2.9 on 2026-07-30 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0008_alter_task_recurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.IntegerField(default=0, help_text='Sort order in pickers/lists')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(blank=True, help_text='The day this content is planned to go out', null=True)),
                ('pillar', models.CharField(blank=True, help_text='Content pillar / theme (free text)', max_length=100)),
                ('content_type', models.CharField(blank=True, choices=[('reel', 'Reel / Short'), ('carousel', 'Carousel'), ('single_image', 'Single image'), ('story', 'Story'), ('video', 'Video'), ('live', 'Live'), ('text', 'Text / Thread')], max_length=20)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('hook', models.TextField(blank=True, help_text='Opening line / scroll-stopper')),
                ('caption', models.TextField(blank=True)),
                ('call_to_action', models.CharField(blank=True, max_length=255)),
                ('hashtags', models.TextField(blank=True)),
                ('tags_links', models.TextField(blank=True, help_text='Accounts to tag, links to include')),
                ('audio_sound', models.CharField(blank=True, help_text='Audio/sound to use', max_length=255)),
                ('image_video_cover', models.FileField(blank=True, help_text='Cover image or video file', null=True, upload_to='content_calendar/')),
                ('content_link', models.URLField(blank=True, help_text='Published URL, once live')),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='idea', max_length=20)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Approval'), ('approved', 'Approved'), ('changes', 'Needs Changes')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(blank=True, help_text='Optional: the business/project this content is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='projects.project')),
                ('platforms', models.ManyToManyField(blank=True, related_name='content_items', to='content_calendar.platform')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
