# Generated by Django 5.2.9 on 2026-07-30 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_calendar', '0002_seed_platforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='', help_text='One or two sentence summary of the voice')),
                ('tone_words', models.JSONField(blank=True, default=list, help_text='List of tone/adjective words')),
                ('sentence_length', models.CharField(choices=[('short', 'Short & punchy'), ('medium', 'Medium'), ('long', 'Long & flowing'), ('varied', 'Varied')], default='varied', max_length=10)),
                ('words_to_avoid', models.JSONField(blank=True, default=list, help_text='Words/phrases this voice never uses')),
                ('sample_paragraphs', models.JSONField(blank=True, default=list, help_text='2-3 distilled sample paragraphs')),
                ('do_notes', models.JSONField(blank=True, default=list, help_text="Do's for writing in this voice")),
                ('dont_notes', models.JSONField(blank=True, default=list, help_text="Don'ts for writing in this voice")),
                ('raw_response', models.TextField(blank=True, default='', help_text='Raw JSON returned by the model')),
                ('enabled', models.BooleanField(default=True, help_text='Apply this voice to generated content')),
                ('distilled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(blank=True, choices=[('reel', 'Reel / Short'), ('carousel', 'Carousel'), ('single_image', 'Single image'), ('story', 'Story'), ('video', 'Video'), ('live', 'Live'), ('text', 'Text / Thread')], help_text="Sets the generated item's content type", max_length=20)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords to steer generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_platforms', models.ManyToManyField(blank=True, help_text='Platforms pre-set on items generated from this template', related_name='content_templates', to='content_calendar.platform')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentTemplatePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_field', models.CharField(choices=[('topic', 'Topic'), ('hook', 'Hook'), ('caption', 'Caption'), ('call_to_action', 'Call to action'), ('hashtags', 'Hashtags')], default='caption', max_length=20)),
                ('prompt', models.TextField(help_text="Instruction for this step, e.g. 'Write a scroll-stopping hook.'")),
                ('order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='content_calendar.contenttemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
