# Generated by Django 5.2.9 on 2026-07-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_calendar', '0003_voiceprofile_contenttemplate_contenttemplateprompt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoiceProfile',
        ),
    ]
