# Generated by Django 5.2.9 on 2026-07-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('gemini', 'Google Gemini')], max_length=20, unique=True)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI provider config',
                'verbose_name_plural': 'AI provider configs',
                'ordering': ['provider'],
            },
        ),
    ]
