# Generated by Django 5.2.9 on 2026-07-17 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('crm', '0004_remove_contact_joined_live_it_list_and_more'),
        ('projects', '0008_alter_task_recurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_type', models.CharField(choices=[('digital_download', 'Digital download'), ('service', 'Service'), ('course', 'Course'), ('membership', 'Membership'), ('other', 'Other')], default='digital_download', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, help_text='The deliverable file, if there is one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='assets.asset')),
                ('project', models.ForeignKey(blank=True, help_text='The business this product belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='projects.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FunnelStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.PositiveIntegerField(default=0, help_text='Order in the funnel, lowest first')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank to use the product's normal price", max_digits=10, null=True)),
                ('is_oto', models.BooleanField(default=False, verbose_name='Is one-time-offer / upsell')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_steps', to='products.product')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='crm.contact')),
                ('funnel_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='products.funnelstep')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.product')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
